<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInit2583c2a9d963920f4596f718ceb9455d
{
    public static $prefixLengthsPsr4 = array (
        'R' => 
        array (
            'RobRichards\\XMLSecLibs\\' => 23,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'RobRichards\\XMLSecLibs\\' => 
        array (
            0 => __DIR__ . '/..' . '/robrichards/xmlseclibs/src',
        ),
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInit2583c2a9d963920f4596f718ceb9455d::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInit2583c2a9d963920f4596f718ceb9455d::$prefixDirsPsr4;

        }, null, ClassLoader::class);
    }
}
