<?php
global $f;
$f->library("graphics");
$graph = new Graph(1300,700,'auto');
$graph->graph_theme = null;
$graph->SetScale("textlin");
$graph->SetShadow();
$graph->xaxis->SetTickLabels($meses);
$b1plot = new BarPlot($cant_1_s);
$b1plot->value->Show();
$b1plot->SetLegend($ano1);
$b2plot = new BarPlot($cant_2_s);
$b2plot->value->Show();
$b2plot->SetLegend($ano2);
$gbplot = new GroupBarPlot(array($b1plot,$b2plot));
$graph->Add($gbplot);
$b1plot->SetColor("white");
$b1plot->SetFillColor("#cc1111");
$b2plot->SetColor("white");
$b2plot->SetFillColor("#11cccc");
$graph->title->Set("INGRESOS COMPARATIVOS EN SOLES ".$ano1." / ".$ano2);
$graph->title->SetFont(FF_VERDANA,FS_BOLD,12);
$graph->Stroke(_IMG_HANDLER);
$graph->img->Stream(IndexPath."/temp/cjgc1.png");

/** Segundo */
$graph2 = new Graph(1300,700,'auto');
$graph2->graph_theme = null;
$graph2->SetScale("textlin");
$graph2->SetShadow();
$graph2->xaxis->SetTickLabels($meses);
$b1plot2 = new BarPlot($cant_1_d);
$b1plot2->value->Show();
$b1plot2->SetLegend($ano1);
$b2plot2 = new BarPlot($cant_2_d);
$b2plot2->value->Show();
$b2plot2->SetLegend($ano2);
$gbplot2 = new GroupBarPlot(array($b1plot2,$b2plot2));
$graph2->Add($gbplot2);
$b1plot2->SetColor("white");
$b1plot2->SetFillColor("#cc1111");
$b2plot2->SetColor("white");
$b2plot2->SetFillColor("#11cccc");
$graph2->title->Set("INGRESOS COMPARATIVOS EN DOLARES ".$ano1." / ".$ano2);
$graph2->title->SetFont(FF_VERDANA,FS_BOLD,12);
$graph2->Stroke(_IMG_HANDLER);
$graph2->img->Stream(IndexPath."/temp/cjgc2.png");
/********/
$f->library('pdf');
$pdf=new FPDF('L','mm','A4');
$pdf->AddPage();
$pdf->SetFont('Arial','',15);
$pdf->SetXY(40,10);
$pdf->Cell(10,0);
$pdf->SetXY(0,25);
$pdf->Image('temp/cjgc1.png' , 10 ,15, 280 , 170,'PNG');
$pdf->AddPage();
$pdf->Image('temp/cjgc2.png' , 10 ,15, 280 , 170,'PNG');
$pdf->Output();